### ISSUE TITLE
JWT guide should use `transportSecurity` feature not `ssl` feature in `server.xml`

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#102]
In the MP JWT guide, the `server.xml` uses the `ssl-1.0` feature. But KC says that [`transportSecurity-1.0` supersedes `ssl-1.0`](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_ssl.html). The [transportSecurity feature doc](https://www.openliberty.io/docs/ref/feature/#transportSecurity-1.0.html) implies that the `ssl` feature is maybe internal rather than the feature that should be specified in the `server.xml`.

We should probably be using the `transportSecurity-1.0` instead of `ssl-1.0` in the MP JWT guide `server.xml`.

**Comment by yeekangc** [comment]
@gkwan-ibm, can you please take a look and prioritize this to be fixed ASAP?
