### ISSUE TITLE
Update MP JWT app to use MP Rest Client

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#105]
The MP JWT guide was created before the MP Rest Client feature was released. The MP JWT guide app needs to be updated to use the MP Rest Client for its secure client. Also maybe update the text in the guide to suggest comparing the system client class in the MP JWT guide (secured) with the same class in the MP Rest Client guide (unsecured) so that the reader can see the differences?

Making this change was not possible previously because the MP Rest Client didn't handle the JwtHeader, I think, but you can now manually propagate it at least: https://github.com/eclipse/microprofile-rest-client/issues/16

**Comment by yeekangc** [comment]
@andymc12 indicated that auto-propagation of headers is now supported for JAX-RS resource.

A MP Config property can be used to tell MP Rest Client to propagate the Auth header.  See https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/integration.asciidoc

**Comment by griffinhadfield** [comment]
This issue has been addressed as part of the guide's rewrite which can be seen on the `vertex-jwt-branch`
