### ISSUE TITLE
Update MP JWT guide to use MP Config for validation

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#106]
The MP JWT guide currently uses mpjwt-1.0-style config in the `server.xml`:

```
<mpJwt id="jwtUserConsumer" keyName="default" audiences="simpleapp"
           issuer="${jwt.issuer}"/>
```
Since the MP JWT guide was written, we've release MP Config. It's best practice to externalise properties with MP Config for portability of microservices.

I think the MP JWT guide should demonstrate best practice and be updated to use MP Config properties instead of the `server.xml` config.

Emily (in a related discussion) said the mpjwt-1.0 server.xml config attributes map to the mpjwt-1.1 MP Config properties:

>mpJwt-1.1 continue supporting the existed <mpJwt …> configuration attributes.
>Configuration from <mpJwt ….> in server.xml overrides equivalent mp-configuration properties
>jwksUri and keyName overrides mp.jwt.verify.publickey.location and mp.jwt.verify.publickey
>issuer overrides mp.jwt.verify.issuer
>Example: In following configuration, validation key is resolved with jwksUri from <mpJwt ..> in server.xml, and mp.jwt.verify.publickey.location will be ignored.
>mp.jwt.verify.publickey.location=/publicKey4k.pem
>`<mpJwt   jwksUri=“https://example.com/api/jwk”      ……..>`

Does this update to the MP JWT guide sound reasonable @yeekangc @Emily-Jiang

**Comment by yeekangc** [comment]
Tagging @chunlongliang-ibm for his thoughts too.

If these properties may be externally configured or updated before deployment, it makes sense to have them as MP Config properties and we should update.

Won't be dynamic but will be provided or can be fed in from external source.

**Comment by chunlongliang-ibm** [comment]
It does make sense to update the guide. 1. Now open liberty has openid connect provider feature, so the guide can be updated to request JWT from OP instead of self-issued JWT. 2. The micro service can be configured to consume JWT with either mp-config or server.xml

**Comment by griffinhadfield** [comment]
This issue has been addressed as part of the guide's rewrite which can be seen on the `vertex-jwt-branch`
