### ISSUE TITLE
MP JWT guide should use defaultKeyStore without overriding keystore type

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#109]
In the "Securing backend services" section - the server.xml gives the `defaultKeyStore` value in the `keyStore` config element. However, it then specifies a keystore of type JCEKS:

```
<keyStore id="defaultKeyStore" location="keystore.jceks" type="JCEKS"
              password="secret" />
```

Since this guide was written, the default keystore type created by Liberty has been switched to the more industry-wide PKCS12 (not JKS - the previous default - or JCEKS); see https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_sec_keystores.html.

I think the guide app should therefore follow this default (auto-creates a PKCS12 keystore and SSL certificate on server start). Also, according to https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_liberty_ssl_defaults.html, you don't need to provide any more detail than id and password - if this is true, should we keep the guide config simple and remove the location and type values? I don't think it's critical to understanding the JWT guide that you understand the details of the keystore - it's complicated enough as it is without additional detail in the server.xml (esp if it's implying you do need to set attributes that you don't actually need to set).

@yeekangc @chunlongliang-ibm Does this make sense to you? Or is there a good reason not to just use the default keystore here?

**Comment by griffinhadfield** [comment]
This issue has been addressed as part of the guide's rewrite which can be seen on the `vertex-jwt-branch`
