### ISSUE TITLE
Update MP JWT guide to use new LMP 3.x

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-jwt#113]
Update the guide to use dev mode
  - need to investigate how to generate the keystore etc.
  - use latest mp
  - use jakartaee
  - ideal pom
  - index.html 
  - remove jdk9+ dependencies 
    - https://github.com/OpenLiberty/guides-common/issues/459
  - plus all existing issues if possible

**Comment by gkwan-ibm** [comment]
- application was reviewed by GK
- working on the README

**Comment by gkwan-ibm** [comment]
- design review meeting will be on next Tue

**Comment by griffinhadfield** [comment]
Proposed outline has been reviewed and approved by SME and stakeholders. 

The changes include the following:
 - Removing inventory service 
    - Have the frontend directly interact with the system service 
- Adding more focus on the frontend
    - How the JWT is built 
    - How the JWT is added to the header of the request 

The proposed changes to the flow of the guide will take the following form: 
![Slide1](https://user-images.githubusercontent.com/38739044/90639355-8c4baf80-e1fc-11ea-8822-8e42ff21aa97.png)

Work is beginning now to make these changes.

**Comment by gkwan-ibm** [comment]
- prototyped the app 
- drafting the README

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- addressing dev content review

**Comment by gkwan-ibm** [comment]
- ready for the dev content review

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
- addressed the dev content review
- finding a better test solution by using vertx

**Comment by gkwan-ibm** [comment]
- peer review
  - Win (Meswan) - in progress
  - Linux (Austin) - in progress

**Comment by gkwan-ibm** [comment]
- ask SME review after end-to-end test

**Comment by gkwan-ibm** [comment]
- SME in progress

**Comment by gkwan-ibm** [comment]
- addressed SME reviewed
- next user review

**Comment by gkwan-ibm** [comment]
- user review completed
- final content and ID review in progress

**Comment by gkwan-ibm** [comment]
- final content and ID review completed

**Comment by gkwan-ibm** [comment]
- final end-to-end test completed
- ready to sign-off

**Comment by yeekangc** [comment]
@griffinhadfield, can you update and close all relevant issues that have been addressed and merged?

**Comment by griffinhadfield** [comment]
The following issues in this repo have been addressed and subsequently closed as part of this rewrite: 

https://github.com/OpenLiberty/guide-microprofile-jwt/issues/119
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/109
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/108
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/106
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/105
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/71
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/34

**Comment by yeekangc** [comment]
We should clean up unneeded branches at the end of this exercise too.

**Comment by yeekangc** [comment]
I noticed 3 hotspots that aren't typical use of hotspots.  Can we change them?

> Each test makes three requests to its associated endpoint. The first request
> has a JWT with the [hotspot=adminRequest1 hotspot=adminRequest2 hotspot=adminRequest3
> file=0]`admin` role. The second request has a JWT with the [hotspot=userRequest1
> hotspot=userRequest2 hotspot=userRequest3 file=0]`user` role. The third request has
> [hotspot=nojwtRequest1 hotspot=nojwtRequest2 hotspot=nojwtRequest3 file=0]`no
> JWT` at all.

**Comment by griffinhadfield** [comment]
@yeekangc would it be a viable solution be to hotspot `request` in each of those sentences instead? The hotspot would be highlighting the following line of code: 
> Response response = makeRequest(urlUsername, authHeaderAdmin);

**Comment by yeekangc** [comment]
May be 'makeRequest' request.  For example, "the first 'makeRequest' request ..."

**Comment by yeekangc** [comment]
Also, we should exclude .vscode, right?

**Comment by griffinhadfield** [comment]
@yeekangc I have updated the previously mentioned hotspots. These paragraph is now as follows: 

<img width="775" alt="image" src="https://user-images.githubusercontent.com/38739044/100124202-59433880-2e49-11eb-9298-60e7790f35f8.png">

I avoided saying "`makeRequest()` request" and instead used "`makeRequest()` call" because the use of the word "request" started to sound repetitive.

**Comment by yeekangc** [comment]
We can probably make 'no JWT' normal text.  LGTM.

I pushed some changes: https://github.com/OpenLiberty/guide-microprofile-jwt/commit/6c99036cd21d7423c1532e80ce5d44120b2c6a57

Good with the changes otherwise.  Thank you!

**Comment by gkwan-ibm** [comment]
close 
- the update was published
