### ISSUE TITLE
Doc links for JWT guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#119]
On the draft docs site (make sure it’s showing the ‘latest’ version) there’s a Security section in the docs which contains, among other topics:
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/authentication.html - contains a diagram that might be a useful basis for your app diagram?
- https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/single-sign-on.html - introduces SSO methods, inc a section on JWT and how MP JWT contributes.

On the final published site, there are no security topics published yet (we're trying to get them finished and published as soon as possible). So, ideally you'd be able to link to the topics but it will depend when you republish your guide (if the doc topics aren't published by the time you republish your guide, we'll have to leave them out and update it later).

**Comment by griffinhadfield** [comment]
The SSO documentation has been added to the guide.
