### ISSUE TITLE
Dev content review for the no-inventory branch

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-jwt#122]
- **Try what you’ll build**
  - [x] Usually this section is a subsection under **Getting started** section
  - [x] "In a new tab of your command-line session, navigate ..." -> "Open another command-line session and navigate..."
  - [x] add following after `mvn liberty-run` (see the jaeger guide)
    - After you see the following message in both command-line sessions, both of your services are ready:
      `The defaultServer server is ready to run a smarter planet.`
  - [x] "...from the `frontend` and `system` directories..." => "...from the `finish` directory..."
- **Configuring MicroProfile JWT**
  - [x] "In a new tab of your command-line session, navigate ..." -> "Open another command-line session and navigate..."
- **Creating a client to access the secure system service**
  - [x] `frontend/src/main/java/io/openliberty/guides/frontend/client/SystemClient.java` in the command is not right
  - [x] `frontend/src/main/java/io/openliberty/guides/frontend/ApplicationBean.java` in the command is not right
  - [x] format ApplicationBean.java better. In the right pane, 
    - no space line between methods
    - `ApplicationBean{` better have a space
    - `public String getUsername() {` not align with other methods
  - [x] format LoginBean.java
- **Testing the application**
  - [ ] if possible add tests
- For the application
  - [x] login page, "Submit" -> "Login"
  - [x] the table is too long, Austin fixed for the master
  - [x] I logged in by bob but the Name field in the table showed me my id. Either rename the field or return `bob`
  - [x] start server.xml should not have mpJwt feature
  - [x] start microprofile-config.properties and SystemResource.java should not be exist (the directory should)
- [x] make sure end-to-end works
- [ ] make sure to address #119 
- [x] try all platforms (tested on Mac and Windows)
- [x] try different browsers, Safari, Chrome, Firefox

**Comment by griffinhadfield** [comment]
For `make sure to address #119`, I am waiting until the documentation is published before I add it to the README.
