### ISSUE TITLE
Dev content review for the manual-jwt-build branch

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-jwt#126]
- **What you’ll learn**
  - [x] "...to validate security tokens in the `system` and inventory microservices." -> "...to validate security tokens in the system microservice."
    - tokens or token?
  - [ ] in the diagram, is it better to switch the arrow direction for the Retrieve JWT?
  - [x] backtick `frontend` in the whole content if "service" follows it, i.e. `frontend` service
    - it is because `frontend` is a service and project
- **JSON Web Tokens for authorization and authentication**
  - suggest to change `xxxxx.yyyyy.zzzzz` to `hhhhh.ppppp.sssss` (although https://jwt.io/introduction/ use xyz)
  - [x] "In our case, ..." no first personal words, e.g. our, we, I, etc...
  - [x] "The user will sign into the frontend application ..." -> "The user will sign into the `frontend` service ..."
  - [x] "... frontends public key ..." frontends should be singular or plural?
- **Try what you’ll build**
  - [x] do as same as the jaeger guide "...navigate to the `finish/frontend`..."
    - similar to the system
- **Configuring MicroProfile JWT**
  - [x] Move "Navigate to the start directory to begin." before "Add the MicroProfile JWT feature..."
  - [x] "Navigate to the `frontend` directory..." -> "Navigate to the `start/frontend` directory..."
    - similar to the system
  - [x] "... the `iss` (issuer) claim..." -> "... the issuer claim..."
- **Creating a client to access the secure system service**
  - [x] no short form for "app"
  - [x] would you reword the paragraph under the "Create the ApplicationBean class" command?
    - sorry, it is a bit hard for me to understand
   - [x] "... included in the com.ibm.websphere.security.jwt package. " is no need
     - "The JWT is built by using `JwtBuilder` APIs in the `buildJwt()` method ." 
  - [x] in LoginBean.java, better not use wild card for import statements
```
  import javax.servlet.*;
  import javax.servlet.http.*;
  import com.ibm.websphere.security.jwt.*;
```
- **Building and running the application**
  - [x] what users should do to see what the guide says for the following?
    - "You can see the header, which contains information about the JWT:" 
    - "And you can see the payload which contains the claims:"

- **Testing the application**
  - in SystemEndpointIT.java
    - [x] right pane no need to show the license comment
    - [x] there is a line wrapped
    - [x] Need to explain why 3 errors in the test output
    - [x] not hard-coded `localhost` and `8080`
    - **Running the tests**
      - [x] "press the enter/return key from the system directory to run the tests. " not clear
        - should say "press the enter/return key from the command-line session of the `system` service to run the tests. "
- add the social login guide to `:page-related-guides:`

**Comment by griffinhadfield** [comment]
Regarding 
> in the diagram, is it better to switch the arrow direction for the Retrieve JWT?

I think it may be best to keep the arrow as it is. The general pattern in this diagram is that the arrow comes from the entity making the action/request , and the arrow points to the entity fulfilling the action/request. If the arrow were to point from the http session to the application bean, I think it may look like the http session is getting the JWT from the application bean, which is the opposite. 

A potential change would be rewording it from "Retrieve JWT" to "Fetch JWT" 

What do you think @gkwan-ibm?

**Comment by gkwan-ibm** [comment]
I feel from session to app bean make more sense, we can use different color.

**Comment by gkwan-ibm** [comment]
- **JSON Web Tokens for authorization and authentication**
  - [ ] "In this case, we will be using JWTs..." no first personal words, e.g. our, we, I, etc...
- **Creating secure system service**
  - [ ] "... at the `/jwtRoles` endpoint. " `/jwtRoles` does not match the code `@Path("/jwtroles")`
- **Creating a client to access the secure system service**
  - [ ] "Create a RESTful client interface for the `system` service." -> "Create a RESTful client interface for the `frontend` service."
  - [ ] the following statement structure is too complex by acronlix check. 
    - The @HeaderParam annotation is used to specify that the value of the String authorization parameter of these methods is used as the Authorization header of requests made to the system service through this client.
  - [ ] "The authHeader is the JWT with Bearer prepended to it ..." May make clear what the "it" is
  - [ ] "...and is included in the Authorization header of the subsequent requests made by the `SystemClient instance`."
    - to "...header of the subsequent requests made by the `SystemClient` instance."
    - or is it clear if change to  "...header of the subsequent requests made by the `defaultRestClient`"?
  - [ ] "The JWT is built using the JwtBuilder`APIs in the [hotspot=buildJwt file=2]`buildJwt() method." is incorrect
