### ISSUE TITLE
Peer review for vertx-jwt-build branch (Linux)

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guide-microprofile-jwt#127]
Functionality
---
- [x] Check that the guide has working instructions and sample code
- [ ] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [ ] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check that the pom.xml, server.xml, etc files are clean
    - [ ] Remove any dependencies and features that are not required
    - [x] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/master/finish/pom.xml
- [x] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [x]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.2</version>
    </plugin>
```
- [ ] Check that there are 4 spaces per indent for proper formatting
- [ ] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [ ] Check the consistency of guide with the template and other guides
- [ ] Check the quality of code according to the best coding practices
- [ ] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [x] Check that the directories are properly structured
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

---

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [ ] Check the appearance of the guide on test site for the following items: 
    - [x] Table of contents 
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [ ] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by AustinSeto** [comment]
# Getting Started

- [ ] I think when asking the user to start the application in the "try what you'll build" section, the code blocks should include the `cd` commands. For example:
```
cd finish/frontend
mvn liberty:run
```

**Comment by AustinSeto** [comment]
# Code

- [ ] Get following warning in frontend, see this PR and associated issue on another guide https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/29
```
[INFO] [WARNING ] SRVE0190E: File not found: /favicon.ico
```

**Comment by griffinhadfield** [comment]
> I think it's better to say "period" rather than "dot"

I think in this case they are just dots not periods. I think periods are just for ending sentences, but for web related things people just say dot, ie "dot com"

>  I think when asking the user to start the application in the "try what you'll build" section, I think we should consider if the code blocks should include the cd commands to distinguish them and make it more obvious. For example:

I believe Gilbert wanted me to follow the format in `guide-microprofile-opentracing-jaeger` which doesn't include it in the command. I will double check with him. 

> Related to OpenLiberty/guides-common#367 but if possible we want to suppress error messages printed by tests

In Gilbert's feedback he just said to make sure to mention that the error messages are expected and what they are from. I can double check. 

> The term groups claims has the code formatting with backticks, unsure if there is supposed to be a hotspot to the @Claim("groups") line in SystemResource.java

I added the backticks because it is a key name within the JWT object. All is okay for this one.

**Comment by AustinSeto** [comment]
Reviewed changes pushed to branch, all critique addressed, closing issue
