### ISSUE TITLE
Peer review for vertx-jwt-build branch (Win)

### ISSUE THREAD

**Issue by meswan** [OpenLiberty/guide-microprofile-jwt#128]
Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [ ] If any URL visits, try `curl` command where applicable 

Formatting & Presentation
---

`README.adoc` checks:
- [ ] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
- [ ] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check that the pom.xml, server.xml, etc files are clean
    - [ ] Remove any dependencies and features that are not required
    - [ ] Ensure that the parent pom.xml files do not contain any dependencies, and all dependencies are specified in the children pom.xml files
- [x] Examples with the right outcomes are provided
- [ ] Example with the wrong outcomes, if any, are provided

`pom.xml` checks (if files are present):
- [x] Check that the file follows the template found here: https://github.com/OpenLiberty/draft-guides-template/blob/master/finish/pom.xml
- [x] Check that the following dependencies are included in all of the `pom.xml` files:
```
<!-- Provided dependencies -->
<dependency>
  <groupId>jakarta.platform</groupId>
  <artifactId>jakarta.jakartaee-api</artifactId>
  <version>8.0.0</version>
  <scope>provided</scope>
</dependency>

<dependency>
  <groupId>org.eclipse.microprofile</groupId
  <artifactId>microprofile</artifactId>
  <version>3.3</version>
  <type>pom</type>
  <scope>provided</scope>
</dependency>
```
- [ ]  Check that the versions of plugins are directly provided and not fed in by a file property.
  - Not formatted like so:
```
    <properties>
        <!-- Plugins -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
    </properties>

    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>${version.liberty-maven-plugin}</version>
    </plugin>
```
  - Should be formatted like so:
```
    <!-- Liberty plugin -->
    <plugin>
        <groupId>io.openliberty.tools</groupId>
        <artifactId>liberty-maven-plugin</artifactId>
        <version>3.2</version>
    </plugin>
```
- [x] Check that there are 4 spaces per indent for proper formatting
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable

Overall checks:
- [x] Check the consistency of guide with the template and other guides
- [x] Check the quality of code according to the best coding practices
- [x] Check that all licensing statements are properly stated in all files, with the correct year (Should be present in all Java files + the `index.html`)
- [x] Check that the directories are properly structured
- [ ] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [ ] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

---

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [ ] Additional tests where applicable: 
    - [ ] Define test coverage and review with team (including guide contributor, if available)
    - [ ] Define detail test cases 
    - [ ] Consider corner cases targeting the specific guide
    - [ ] Consider corner cases UI tests
    - [ ] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [ ] Consider testing the `curl` command for URL visits
- [ ] Consider building with both Maven and Gradle build tools 
- [ ] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
    - [ ] Table of contents 
    - [ ] Headings
    - [ ] Paragraphs
    - [ ] code snippets
    - [ ] outputs
    - [ ] links
    - [ ] hotspots 
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by meswan** [comment]
Frontend, if these are expected, then we should add a note clarifying that:

```
[WARNING] The C:\Users\Meswan\Desktop\guide-microprofile-jwt\start\frontend\src\main\liberty\config\server.xml file is overwritten by the C:\Users\Meswan\Desktop\guide-microprofile-jwt\start\frontend\src\main\liberty\config\server.xml file.
```

```
[INFO] Failed to find runtime version
```
```
warning: unknown enum constant ConfigurationPolicy.IGNORE
  reason: class file for org.osgi.service.component.annotations.ConfigurationPolicy not found
warning: unknown enum constant ReferencePolicy.DYNAMIC
  reason: class file for org.osgi.service.component.annotations.ReferencePolicy not found
warning: unknown enum constant ReferenceCardinality.OPTIONAL
  reason: class file for org.osgi.service.component.annotations.ReferenceCardinality not found
warning: unknown enum constant ReferencePolicyOption.RELUCTANT
  reason: class file for org.osgi.service.component.annotations.ReferencePolicyOption not found
warning: unknown enum constant ConfigurationPolicy.IGNORE
  reason: class file for org.osgi.service.component.annotations.ConfigurationPolicy not found
warning: unknown enum constant ReferencePolicy.DYNAMIC
  reason: class file for org.osgi.service.component.annotations.ReferencePolicy not found
warning: unknown enum constant ReferenceCardinality.OPTIONAL
  reason: class file for org.osgi.service.component.annotations.ReferenceCardinality not found
warning: unknown enum constant ReferencePolicyOption.RELUCTANT
  reason: class file for org.osgi.service.component.annotations.ReferencePolicyOption not found
warning: unknown enum constant ConfigurationPolicy.IGNORE
  reason: class file for org.osgi.service.component.annotations.ConfigurationPolicy not found
warning: unknown enum constant ReferencePolicy.DYNAMIC
  reason: class file for org.osgi.service.component.annotations.ReferencePolicy not found
warning: unknown enum constant ReferenceCardinality.OPTIONAL
  reason: class file for org.osgi.service.component.annotations.ReferenceCardinality not found
warning: unknown enum constant ReferencePolicyOption.RELUCTANT
  reason: class file for org.osgi.service.component.annotations.ReferencePolicyOption not found
C:\Users\Vashish\Desktop\guide-microprofile-jwt\start\frontend\src\main\java\io\openliberty\guides\frontend\filters\NoCacheFilter.java:26: error: NoCacheFilter is not abstract and does not override abstract method destroy() in Filter
public class NoCacheFilter implements Filter {
       ^
1 error
12 warnings
```

system warning:
```
[INFO] Compiling 1 source file to C:\Users\Vashish\Desktop\guide-microprofile-jwt\start\system\target\test-classes
[WARNING] /C:/Users/Vashish/Desktop/guide-microprofile-jwt/start/system/src/test/java/it/io/openliberty/guides/system/util/JwtBuilder.java: C:\Users\Vashish\Desktop\guide-microprofile-jwt\start\system\src\test\java\it\io\openliberty\guides\system\util\JwtBuilder.java uses or overrides a deprecated API.
[WARNING] /C:/Users/Vashish/Desktop/guide-microprofile-jwt/start/system/src/test/java/it/io/openliberty/guides/system/util/JwtBuilder.java: Recompile with -Xlint:deprecation for details.  
```

**Testing the application**
`trigger a failure if a change introduces a defect.` consider rewording to `trigger a failure if a breaking change is introduced.`

Check if test section can be simplified by already included the java file instead of asking user to create so that it is not as lengthy.

**Comment by gkwan-ibm** [comment]
`[INFO] Failed to find runtime version` is OL 20.0.0.9 issue. It should be fixed by 20.0.0.10

**Comment by gkwan-ibm** [comment]
warnings issue will be addressed by https://github.com/OpenLiberty/open-liberty/issues/14154

**Comment by griffinhadfield** [comment]
The following warning has been fixed:

```
C:\Users\Vashish\Desktop\guide-microprofile-jwt\start\frontend\src\main\java\io\openliberty\guides\frontend\filters\NoCacheFilter.java:26: error: NoCacheFilter is not abstract and does not override abstract method destroy() in Filter
public class NoCacheFilter implements Filter {
```
