### ISSUE TITLE
Content review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/guide-microprofile-jwt#135]
Looking good! Review comments from myself and @lauracowen:  

## What you'll learn
- Are we not using an `inventory` service in this guide? I'm assuming that's to simplify it? 

## JSON Web Tokens for authentication and authorization
- I don't think we should have this section in the guide. Maybe include the information from the first paragraph of this section after the first paragraph of the **What you'll learn** section.
- I don't think we need all this info about JWT tokens in the guide at all. It's not the place of the guide to provide documentation beyond what's needed to understand the guide. I think the guide should instead link to https://openliberty.io/docs/latest/single-sign-on.html. This SSO topic isn't live yet, but it'll be published on Friday. Could also link to https://jwt.io/introduction/.
- The paragraph that starts with, "In this case..." looks useful and could move to the **What you'll learn** section.
- The last paragraph in this section is describing how the app works. Could we also move this to the **What you'll learn** section following the diagram, and maybe make it slightly more concise if possible?

## Try what you'll build
- "Log in with one of the following user information credentials:" --> "Log in with one of the following usernames and and its corresponding password:"? - I'm assuming that you don't need the role information to log in? 
- Table formatting needs fixing.

## Configuring MicroProfile JWT
- This section also needs to go before the **Building and running the application** section. It's not interesting enough to be upfront. The [REST intro guide](https://openliberty.io/guides/rest-intro.html#configuring-the-server) is a good example of guide structure. Just make sure any subsequent references to the `config.properties` file make sense with the config going to the end of the guide. It's fine to say "this configuration will be created later in the guide" or something like that.

## Creating secure system service
- Update this section title to "Creating the secure system service".
- Start this section with a sentence to give context by reminding the reader what the secure `system` service is and does.

## Creating a client to access the secure system service
- Don't need "SystemClient" hot-spotted in "...all their associated method of the SystemClient class..."
- Only hot-spot "authHeader" the first time that it's mentioned.

## Building and running the application
- Table formatting needs fixing.

## Nice work! Where to next?
- Take out "Next, you can try one of the related MicroProfile guides. They demonstrate technologies that you can learn and expand on what you built here." - There are already links to other guides, and I don't think it's standard for the guides to have this extra info at the end.

**Comment by griffinhadfield** [comment]
Feedback has been addressed in the this PR: https://github.com/OpenLiberty/guide-microprofile-jwt/pull/136
