### ISSUE TITLE
Update to use MP JWT 1.2

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-jwt#140]

**Comment by gkwan-ibm** [comment]
hi @teddyjtorres 
Beside update the pom.xml and server.xml to use the latest version, would you tell us what new thing we may add into [the existing guide](https://openliberty.io/guides/microprofile-jwt.html) for mpJwt-1.2?

**Comment by gkwan-ibm** [comment]
close
- the [guide](https://openliberty.io/guides/microprofile-jwt.html) was updated
