### ISSUE TITLE
Feedback 3/9 

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/guide-microprofile-jwt#29]
- [x] long, can be at least 30 min.
Discussed and we average it with Anna's feedback (15-20 min) so change to 25)
- [x] Move the sentence that states you can not access backend service to "Try what you ..." section
 * Extra, my understanding from the little and the first sentences after the title and what you will learn section , is that we will see the resources first and then we will secure them. But as i walk through the guide, it does not tell us that. 
- [x]  there are some pointers in the guide, like following , here
Pending on "following" cuz it was not objected by any ID
- [x] imports are spaced in the code, also remove comments like //JWT Imports 
- [x] what is `aud` in the first table? 
- [x] ur file paths has something like `/start/backendServices  ...`, it should start with `backendServices/....`. same for other paths.
- [x] I am not sure but we can reduce the repeated information for "Building and running the application" section. It is repeating the same thing as in try what you will build section. (actions are the same, no small difference). I suggest we reference that rathar than making users to read again.
- [x] Creating the files should follow the convention like,  
Create the test class class for the inventory service in the `backendServices/src/test/java/it/io/openliberty/guides/jwt/InventoryEndpointTest.java`file: , should the same for the rest
- [x] HTTP requests should be backticked -> `GET`

**Comment by JunyiSun** [comment]
@Ahmad-Ayyoub 
Can you review them again and see if issues are addressed?
