### ISSUE TITLE
Fix "only authenticated users with admin and user"

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-jwt#32]
https://twitter.com/OmniFaces/status/978977537022988289

> 
> OmniFaces @OmniFaces
> @OpenLibertyIO "The @RolesAllowed({"admin", "user"}) annotation allows only authenticated users with admin and user"
> 
> Should that not be "admin or user" for clarity?

**Comment by JunyiSun** [comment]
fixed by #33
