### ISSUE TITLE
The JWT guide needs some architectural diagrams

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/guide-microprofile-jwt#34]
Some high level diagrams are needed to illustrate the architecture of the example services. This probably applies to the other guides as well.

**Comment by proubatsis** [comment]
![image](https://user-images.githubusercontent.com/8409464/41976142-48b6d8a2-79ea-11e8-9b04-4136f415be44.png)

@JunyiSun @evelinec How does this look?

**Comment by evelinec** [comment]
@tevans78 and @lauracowen can you take a look at the diagram above and let us know what you think as an architectural diagram for the JWT guide? Thank you.

**Comment by JunyiSun** [comment]
<img width="1027" alt="screen shot 2018-05-25 at 11 04 24 am" src="https://user-images.githubusercontent.com/12009928/44591874-dd02ac00-a78c-11e8-93b9-67a7d369b14d.png">

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by lauracowen** [comment]
It took me ages to work out how many microservices there are in this app and what each one does. I think it would've helped to have had a diagram (or more than one) showing:

- how many and what microservices are in the app - what are their main purposes? (eg inventory does xxx, system does yyy, frontend provides login and builds JWTs that are used to authorise access to information requested from and by the other two microservices)
- what's the main flow of JWTs as they're passed back and forth when requests are made for information about a particular host (eg from the frontend to the inventory service, and the inventory to the system service)?

**Comment by griffinhadfield** [comment]
This issue has been addressed as part of the guide's rewrite which can be seen on the `vertex-jwt-build` branch.
