### ISSUE TITLE
The front end UI for the JWT guide needs more features to demonstrate the propagation

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/guide-microprofile-jwt#35]
The frontend UI only allows you to log in and log out. Since you can not go directly to the backend urls, the UI needs some more function to demonstrate that things art working properly.

**Comment by evelinec** [comment]
@JunyiSun to provide guidance for @proubatsis to work on this issue.

**Comment by proubatsis** [comment]
@evelinec #40 
cc @JunyiSun
