### ISSUE TITLE
The JWT example code has java in the resources module

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/guide-microprofile-jwt#36]
The is a test class called JwtVerifier.java in the resources module
```
guide-microprofile-jwt/finish/resources/src/main/java/test/JwtVerifier.java
```
The guide does not make it clear what this class is for. I suspect that it could be moved into the backend module.

**Comment by evelinec** [comment]
@JunyiSun to provide guidance for @proubatsis to work on this issue.

**Comment by proubatsis** [comment]
@JunyiSun @evelinec #46
