### ISSUE TITLE
Distracting syntax highlighting

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guide-microprofile-jwt#43]
For server.xml features, the feature version strings are highlighted different from the xml element and the rest of the contents.  E.g. the part I show in the ** is a different colour on the site
```
<feature>jsonp**-1.0**</feature>
<feature>cdi**-1.2**</feature>
```
Whereas the whole feature name should be highilighted
```
<feature>**jsonp-1.0**</feature>
<feature>**cdi-1.2**</feature>
```

This is likely an issue across all the guides.

**Comment by JunyiSun** [comment]
fixed by #48
