### ISSUE TITLE
A few minor suggestions from reading the guide

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guide-microprofile-jwt#44]
[] "locate public key for JWT signature validation". -> locate **the** public key for JWT signature validation

[] When describing "keyName" in the table, it refers to a "truststore in the SSL configuration" but there is no mention of truststore in the server configuration, only keystore.

[] "MicroProfile JWT maps its token claims".  The taken claims aren't MicroProfile JWT's.  Should this say, "MicroProfile JWT maps the claims in JWT". or "MicroProfile maps the JWT claims" or something like....

**Comment by JunyiSun** [comment]
fixed by #48
