### ISSUE TITLE
Clarity on system and inventory services 

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/guide-microprofile-jwt#61]
Within this guide, the system, and inventory services are not explicitly explained. While these are mentioned in previous guides, such as the 'Configuring Microservices' guide, it still may be worth explaining these two services to avoid ambiguity. For example, a user may follow this tutorial prior to following the previous tutorials.

**From the 'Injecting dependencies into microservices' guide:**
> he application that you will be working with is an inventory service, which stores the information about various JVMs that run on different systems. Whenever a request is made to the inventory service to retrieve the JVM system properties of a particular host, the inventory service communicates with the system service on that host to get these system properties. The system properties are then stored and returned.

**Comment by JunyiSun** [comment]
https://github.com/OpenLiberty/guide-microprofile-jwt/pull/63
