### ISSUE TITLE
Incorrect Class Reference

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/guide-microprofile-jwt#62]
In the '**Securing back end services with MicroProfile JWT**' section, within the subsection '**Adding the SecureSystemClient class'**, the guide reads: 

> However, the **SystemClient** class overrides the buildClientBuilder() method by adding the authorization header to the returned builder, return builder.header(HttpHeaders.AUTHORIZATION, authHeader).

Although, the SystemClient class does not override buildClientBuilder() to add the authorization method - the SecureSystemClient class does this. I have provided the code below to show this, with a comment above the line in question.

From 'SystemClient.java':  
```
protected Builder buildClientBuilder(String urlString) {
    try {
      Client client = ClientBuilder.newClient();
      Builder builder = client.target(urlString).request();
      return builder.header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON);
    } catch (Exception e) {
      System.out.println("ClientBuilderException");
      return null;
    }
  }
```

From 'SecureSystemClient.java':
```
    public Builder buildClientBuilder(String authHeader) {
    Builder builder = super.buildClientBuilder(this.url);
    
    //adds the Http Auth methods, not present in superclass
    return builder.header(HttpHeaders.AUTHORIZATION, authHeader);
  }

```

**Comment by JunyiSun** [comment]
#63
