### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-jwt#68]
When ran mvn install, failed

**Comment by yeekangc** [comment]
Saw this too: [WARNING] CWWKM2179W: The application is not defined in the server configuration but the POM configuration indicates it should be installed in the apps folder. Application configuration is being added to the target server configuration dropins folder by the plug-in.

Probably a separate issue to address.  Not sure if we had this previously.

**Comment by gkwan-ibm** [comment]
Justine will help to test a scenario
- download the guide from mp13 branch 
- install with 18002
- download the master
- install with 18003

**Comment by justineechen** [comment]
Tested scenario described above and I did not receive any failing tests.
I ran the following commands and will run them again now to double check:

- `rm -rf ~/.m2/repository`
- `git clone https://github.com/OpenLiberty/guide-microprofile-jwt.git`

- `git checkout remotes/origin/microProfile-1.3`
- (Checked that `server.xml` had `<feature>mpJwt-1.0</feature>`)
- Changed `<version.liberty>RELEASE</version.liberty>` to `<version.liberty>18.0.0.2</version.liberty>` in `pom.xml`
- `mvn clean install`
- **All tests passed**

- Changed `<version.liberty>18.0.0.2</version.liberty>` to `<version.liberty>RELEASE</version.liberty>`in `pom.xml`
- `git checkout origin/master`
- (Checked that `server.xml` had `<feature>mpJwt-1.1</feature>`)
- `mvn clean install`
- I noticed here that maven dependencies were being downloaded here again when I ran mvn clean install
- **All tests passed**

**Comment by gkwan-ibm** [comment]
close this issue
- cannot be reproduced by Justine and I
- the following error is for #37
  - Exception thrown by application class 'javax.faces.webapp.FacesServlet.service:220'
