### ISSUE TITLE
Warnings for dependencyManagement from Maven build

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-jwt#69]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.openliberty.guides:resources:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.version' for io.openliberty.features:features-bom:pom is either LATEST or RELEASE (both of them are being deprecated) @ io.openliberty.guides:microprofile-jwt:0.0.1-SNAPSHOT, /Users/ykchang/repositories/guide-microprofile-jwt/finish/pom.xml, line 40, column 26
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.openliberty.guides:microprofile-jwt:pom:0.0.1-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.version' for io.openliberty.features:features-bom:pom is either LATEST or RELEASE (both of them are being deprecated) @ line 40, column 26
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by yeekangc** [comment]
Maven is dropping the use of LATEST and RELEASE but there is an issue with it for dependencyManagement: https://issues.apache.org/jira/browse/MNG-4463

We should monitor and update as soon as ready to rid of the warnings.

**Comment by gkwan-ibm** [comment]
All guides specified the exact versions in the pom.xml except few guides are pending on dev-mode conversion.
