### ISSUE TITLE
Warning for JCEKS keystore

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-jwt#71]
[WARNING] 
[WARNING] Warning:
[WARNING] The JCEKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /Users/ykchang/repositories/guide-microprofile-jwt/finish/resources/src/main/resources/keystore.jceks -destkeystore /Users/ykchang/repositories/guide-microprofile-jwt/finish/resources/src/main/resources/keystore.jceks -deststoretype pkcs12".
[INFO]

**Comment by griffinhadfield** [comment]
This issue has been addressed as part of the guide's rewrite which can be seen on the `vertex-jwt-build` branch.
