### ISSUE TITLE
Unable to access application when starting server from VM

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-microprofile-jwt#73]
While testing guides for CASCON on the VMs, I noticed that the application could not be accessed when I started the server from the VM.

**Comment by yeekangc** [comment]
@justineechen, can you please post more technical details?  We will need that to reproduce the issue and investigate further.

**Comment by justineechen** [comment]
When I was using the CASCON VM, I tried accessing the application at: http://cascon08.canlab.ibm.com:9090/application.jsf and the browser showed "Cannot connect to Server". `mvn clean install` and `mvn verify` passed, but the application can't be reached this way. 

Eveline said that the application works on the remote GUI.

**Comment by justineechen** [comment]
This issue is with port forwarding and not an issue with the guide itself, so it will be closed.
