### ISSUE TITLE
Quick review comments

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-jwt#77]
Not a thorough re-review but some things I spotted:

- [x] Typo: "comminication"

- [x] Inconsistent app approach: Why are `SystemResource.java` and `InventoryResource.java` included in the `start` directory when the first thing the user does with them is overwrite their content? According to the style of the rest of the guides, these files should not exist (or should be empty placeholders?)  then the user creates them with the code provided in the guide (instead of pasting over the existing content). `SecureSystemClient.java` does it right.

- [x] 'Creating the server configuration file' - The sentence about creating the file should be of the style used in other guides, eg https://openlibertydev.mybluemix.net/guides/rest-intro.html

**Comment by evelinec** [comment]
@justineechen can you fix the typo issue for now? Thanks.

**Comment by MaiHameed** [comment]
See #96
