### ISSUE TITLE
Multipane Issue

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/guide-microprofile-jwt#81]
# What you'll learn
- [x]  JSON Web Token (JWT) is becoming the most common token format because it follows well-defined and known standards. In regards to what
- [x] "inventory service to retrieve the JVM" inventory isn’t highlighted so to be consistent it should
- [x] “inventory service communicates with" next line too

## Try what you'll build
- [x] "git clone https://github.com/openliberty/guide-microprofile-jwt.git" faulty line break
- [x] "Navigate your browser to the front-end web application endpoint" be consistent in your use of "front end" as you use the non-hyphenated version for the rest of the guide
- [x] "You are not authorized to access the inventory service." Drop the period
- [x]  "you cannot access the inventory service in the back end" highlight inventory

## Securing back end services with MicroProfile JWT
- [x] "The mpJwt feature adds the libraries that are required for MicroProfile JWT implementation." Highlight mpWJT to point to 3rd pane.
- [x] "The </mpJwt> element is required to configure the injection of the caller’s JWT." </mpJW> --> <mpJWT/> and it should not highlight the comment above its own tag
- [x] The chart with issuer, audiences, and keyName might as well be in the order you will see them in the 3rd pane…

## Securing system service 
- [x] "Replace the System Resource class file with roles-based access control." Faulty line break after ba in based.
- [x] @RolesAllowed highlights the @Get annotation as well as itself. 
- [x] "Replace the `System Resource` class file with roles-based access control." --> `SystemResource` class

## Securing the inventory service
- [x] @RolesAllowed highlights the @Get as well as itself
- [x] manager.get(hostname, authHeader) highlights a comment above its line
- [x] "Replace the Inventory Resource class file with roles-based access control." --> `InventoryResource` class

## Adding the SecureSystemClient class
- [x] "the inventory service uses the normal" highlight inventory for consistency 
- [x] "Create the Secure System Client class file." Remove "file" from ending
- [x] buildClientBuilder() highlights a comment above it
- [x] return builder.header(HttpHeaders.AUTHORIZATION, authHeader) highlights the bracket below

## Trying more JAX-RS methods to validate tokens
- [x] "Create the JWT Resource file to enable a service that retrieves information from the token." Has a line break before the last t in "that"
- [x] regarding quote above “JWT Resource file" --> "JWTResource class"
- [x] "token by calling the getName()" getName() should probably also point to the one line where it is being used
- [x] "SecurityContext.getUserPrincipal()" highlights the line above itself
- [x] "object in the java.security.Principal type… object is also an instance of the org.eclipse.microprofile.jwt.JsonWebToken type"
- [x] "getGroups() method." Should be highlighted
- [x] "user has the admin role" "admin" should only highlight its own line
- [x]  “Status.FORBIDDEN” should not highlight the bracket below itself 
- [x]   SecurityContext.isUserInRole(String)  should only highlight the if statement
- [x] "jwtPrincipal.getClaim("customClaim")" should only highlight the first line after the if statement
- [x] "Create the `Secure System Client` class."  --> SecureSystemClient

# Building and running the application
- [x] "if you log in as a user without" "user" should be highlighted 

# Testing the application
- [x] "Create the System Endpoint Test class file." --> Create the SystemEndpointTest class
- [x] "Create the Inventory Endpoint Test class file." --> Create the InventoryEndpointTest class 
- [x] "Create the JWT Test class file." --> Create the JWTTest class
- [x] setup() needs to point to the code file
- [x] "whether the user name is" --> username

## Running the tests
- [x] setup() needs to point to the file

# Nice work! You did it!
- [x] "learned how to use MicroProfile JWT to validate JWT" sounds awkward should at least be “jwts”

**Comment by Rachelwrq** [comment]
### Securing back end services with MicroProfile JWT
- [ ] The mpJwt in second paragraph is referring to the dependency in POM file, but the hotspot is referring to the mpJwt feature in a server.xml file

#### Creating the server configuration file
- [ ] In the action arrow: the instruction should be “Create the server configuration file”
- [ ] Need more file formatting for server.xml. 

#### Trying more JAX-RS methods to validate tokens
- [ ] `admin` role does not need to have a hotspot

**Comment by Rachelwrq** [comment]
### Securing back end services with MicroProfile JWT
#### Securing the system service
- [ ] the `SystemResource` in the action arrow should be in backticks

**Comment by andrewdes** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present

**In the README.adoc:**
- [ ] Tags in the front matter are correct
     - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`
     - [ ] seo tag?

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
     - [ ] start directory
     - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
