### ISSUE TITLE
multipane issue

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-jwt#87]
- [x] following urls not open new tab
  - http://localhost:9090/application.jsf
- [x] shown `[hotspot=Status.FORBIDDEN message, ` at "Testing the application" section

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-microprofile-jwt/commit/18404ff122c821fd08572daba63a165bda0e27e3
