### ISSUE TITLE
mvn install liberty:start-server fails: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by nheidloff** [OpenLiberty/guide-microprofile-jwt#92]
Steps to reproduce:
* git clone https://github.com/openliberty/guide-microprofile-jwt.git
* cd guide-microprofile-jwt/finish
* mvn install liberty:start-server

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.631 s <<< FAILURE! - in it.io.openliberty.guides.jwt.JwtTest
[ERROR] testSuite(it.io.openliberty.guides.jwt.JwtTest)  Time elapsed: 1.562 s  <<< ERROR!
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://localhost:5051/inventory/jwt/username: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed

[INFO] Reactor Summary for microprofile-jwt 0.0.1-SNAPSHOT:
[INFO] 
[INFO] microprofile-jwt ................................... SUCCESS [  9.072 s]
[INFO] resources .......................................... SUCCESS [ 10.625 s]
[INFO] backendServices .................................... FAILURE [ 25.035 s]
[INFO] frontendUI ......................................... SKIPPED

-------------------------------------------------------------------------------
Test set: it.io.openliberty.guides.jwt.JwtTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.631 s <<< FAILURE! - in it.io.openliberty.guides.jwt.JwtTest
testSuite(it.io.openliberty.guides.jwt.JwtTest)  Time elapsed: 1.562 s  <<< ERROR!
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://localhost:5051/inventory/jwt/username: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)
Caused by: javax.net.ssl.SSLHandshakeException: SSLHandshakeException invoking https://localhost:5051/inventory/jwt/username: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)
Caused by: java.security.cert.CertPathValidatorException: signature check failed
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)
Caused by: java.security.SignatureException: Signature does not match.
	at it.io.openliberty.guides.jwt.JwtTest.testJwtGetName(JwtTest.java:48)
	at it.io.openliberty.guides.jwt.JwtTest.testSuite(JwtTest.java:42)

**Comment by yeekangc** [comment]
@nheidloff, which Java SDK were you working with?

**Comment by nheidloff** [comment]
$ java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190205_147 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

**Comment by justineechen** [comment]
Hi @nheidloff, I haven't been able to reproduce your issue running on:
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190205_147 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)
```

This might be occurring because you have running servers. Could you try:
- running `mvn liberty:stop-server`
- running `ps -ef | grep java` and `kill` any remaining processes
- rerun `mvn clean install liberty:start-server` 

Thank you!
Justine

**Comment by nheidloff** [comment]
Thanks @justineechen, there were indeed still some java processes running which 'mvn liberty:stop-server' didn't stop.

Now I see another issue:

[INFO] microprofile-jwt ................................... SUCCESS [ 13.362 s]
[INFO] resources .......................................... SUCCESS [ 14.067 s]
[INFO] backendServices .................................... SUCCESS [ 43.949 s]
[INFO] frontendUI ......................................... FAILURE [  0.241 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2019-04-10T08:17:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project frontendUI: Compilation failure: Compilation failure: 
[ERROR] /Users/nheidloff/Desktop/temp/guide-microprofile-jwt/finish/frontendUI/src/main/java/io/openliberty/guides/ui/filters/NoCacheFilter.java: error reading /Users/nheidloff/Desktop/temp/guide-microprofile-jwt/finish/frontendUI/src/main/java/io/openliberty/guides/ui/filters/NoCacheFilter.java; /Users/nheidloff/Desktop/temp/guide-microprofile-jwt/finish/frontendUI/src/main/java/io/openliberty/guides/ui/filters/NoCacheFilter.java (Too many open files)

**Comment by nheidloff** [comment]
When I cd into frontendUI and start the server, it works. Thanks

**Comment by yeekangc** [comment]
Thank you, @nheidloff.

https://github.com/OpenLiberty/guides-common/issues/157 tracks the running server/process issue.  Will see if we can address soon.
